### ISSUE TITLE
go_vet tools/extract.go: invalid syntax

### ISSUE THREAD

**Issue by robotvert** [lukeroth/gdal#16]
Hi,

I'm indexing go packages at [http://libs.club/golang](http://libs.club/golang) and during the code quality report phase (using [this](https://github.com/robotvert/goreportcard)) the following error appeared:

```
(go_vet) strconv.ParseInt: parsing "lukeroth/gdal/tools/extract.go": invalid syntax
```

This file looks mostly useless so there's no consequence whatsoever but I thought I'd let you know.

PS: Your package is not up on the aforementioned website because I've not published the category related to geocoding yet :sweat_smile:

**Comment by martende** [comment]
Removed with commit https://github.com/lukeroth/gdal/commit/729e6c67ba1cb93a6b3d38f1ff5d20ce12098f2a

**Comment by robotvert** [comment]
:+1:
