### ISSUE TITLE
Better document Windows build process?

### ISSUE THREAD

**Issue by wthorp** [lukeroth/gdal#26]
I would really appreciate it if you filled in some blanks on install of your library.  In particular, the GDAL / Go build process on Windows. I can't find pre-built MinGW GDAL builds out there, and Go's linker doesn't appear to support Visual Studio's .lib files.  Do you build GDAL from source?

**Comment by lukeroth** [comment]
I'm not currently building on a Windows machine, but from what I remember, the MinGW builds that are part of the OSGeo4W distribution worked fine for me.
