### ISSUE TITLE
envelope ops (e.g.: union) don't achieve much

### ISSUE THREAD

**Issue by remster** [lukeroth/gdal#30]
https://github.com/lukeroth/gdal/blob/cda1b1bb480461c76cacad8dc1406c822cfbb0d4/ogr.go#L109

They don't return and they modify the by-value (i.e.: copied) receiver ([see:](https://tour.golang.org/methods/4)) which looks like a bug. I had to code around it - would you be interested in me contributing back?

**Comment by lukeroth** [comment]
Added the missing return statements.
