### ISSUE TITLE
Can't determine if OGR return value is null/nil

### ISSUE THREAD

**Issue by jasonsurratt** [lukeroth/gdal#32]
In `ogr.go`, I don't see an exported way to determine if a Feature, Geometry, etc. contains a nil `cval`. In some functions (e.g. `func (layer Layer) NextFeature() Feature`) the only way to check for an error or last result is by checking for a nil/null value.

I'm happy to create a pull request if this is just an omission.

Apologies if this is just user error.

Thanks!

**Comment by aviyu** [comment]
you can add code like this,I did it and it works well.
```go
func (layer Layer) NextFeatureP() *Feature {
	feature := C.OGR_L_GetNextFeature(layer.cval)
	if feature == nil {
		return nil
	}
	return &Feature{feature}
}
```

**Comment by lukeroth** [comment]
This was fixed by a recent pull request, NextFeature now works as in your comment.

**Comment by jasonsurratt** [comment]
@lukeroth Thanks!
