### ISSUE TITLE
Feature request: clip vector layers using OGR

### ISSUE THREAD

**Issue by ljvmiranda921** [lukeroth/gdal#41]
Hello everyone,

I'm planning to clip a vector layer using a raster extent using this library. However, I noticed in [this line](https://github.com/lukeroth/gdal/blob/master/ogr.go#L1548) that it is currently unimplemented. 

This is my original command when using `ogr2ogr`

```s
$ ogr2ogr out.shp in.shp  -clipsrc <extent>
```

I would like to ask:
1. When will the OGR Clip feature be implemented?
2. Is it possible to achieve the task above with the current feature set?

Thank you very much @lukeroth and I appreciate your effort for this library!

**Comment by magtanggol03** [comment]
Hi, were you able to solve this problem?

**Comment by ljvmiranda921** [comment]
Hi @magtanggol03 ,  :laughing: 

I solved it by using the [`SetSpatialFilter`](https://godoc.org/github.com/lukeroth/gdal#Layer.SetSpatialFilter) method!

```go
var shpFile gdal.Layer
var extent gdal.Geometry

shpFile.SetSpatialFilter(extent)
shpFile.ResetReading()

outDriver := gdal.OGRDriverByName("GeoJSON")
outDataSource, _ := outDriver.Create(outpath, []string{})
outDataSource.CopyLayer(shpFile, "Labels", []string{})
outDataSource.Destroy()
```

It does not necessarily cut the shapes, but is workable for my use-case. :smile: 

[Reference implementation](https://github.com/thinkingmachines/tiffany/blob/master/cmd/pipelines.go)

**Comment by ardieorden** [comment]
Thanks for the solution @ljvmiranda921 ! This helped a lot with my use case.

**Comment by ljvmiranda921** [comment]
Closing this issue
