### ISSUE TITLE
install bindings on debian 9 and fedora 32

### ISSUE THREAD

**Issue by therox** [lukeroth/gdal#50]
Trying to build example results in this error (go 1.7)
```
root@02fa1aeeeb6f:/5/src/github.com/lukeroth/gdal/examples/test_tiff# go build
# github.com/lukeroth/gdal
could not determine kind of name for C.OGR_G_Distance3D
root@02fa1aeeeb6f:/5/src/github.com/lukeroth/gdal/examples/test_tiff# gdal-config --version    
2.1.2
root@02fa1aeeeb6f:/5/src/github.com/lukeroth/gdal/examples/test_tiff# echo $GOPATH
/5
```

Fedora 32 (go v1.14) gives more errors:
```
> go build
# github.com/lukeroth/gdal
../../osr.go:1256:13: could not determine kind of name for C.OPTGetParameterInfo
../../osr.go:1220:7: could not determine kind of name for C.OPTGetParameterList
../../osr.go:1198:7: could not determine kind of name for C.OPTGetProjectionMethods
../../osr.go:115:9: could not determine kind of name for C.OSRFixup
../../osr.go:110:9: could not determine kind of name for C.OSRFixupOrdering
../../osr.go:120:9: could not determine kind of name for C.OSRStripCTParms
>  gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```
What I do wrong? How I can fix it?

**Comment by mtfelian** [comment]
I suppose there is something wrong with your library paths. 

You need to provide right LDFLAGS / CFLAGS in your code. Yes, you should have basic C knowledge to work with this.

**Comment by therox** [comment]
> I suppose there is something wrong with your library paths.
> 
> You need to provide right LDFLAGS / CFLAGS in your code. Yes, you should have basic C knowledge to work with this.
> 
> Check whether libgdal is in your /usr/lib or not.

Thank you for your answer. 
Isn't there common setup with LDFLAGS/CFLAGS for this particural bindings?
As for libgdal...
for Debian:
```
# ls -lh /usr/lib/libgd*  
-rw-r--r-- 1 root root 34M Jun 20  2018 /usr/lib/libgdal.a
lrwxrwxrwx 1 root root  17 Jun  3 09:38 /usr/lib/libgdal.so -> libgdal.so.20.1.2
lrwxrwxrwx 1 root root  17 Jun  3 09:38 /usr/lib/libgdal.so.20 -> libgdal.so.20.1.2
-rw-r--r-- 1 root root 15M Jun 20  2018 /usr/lib/libgdal.so.20.1.2
```

and Fedora: 
```
$ ls -lh /usr/lib64/libgdal*
lrwxrwxrwx 1 root root  17 Mar  9 12:50 /usr/lib64/libgdal.so -> libgdal.so.26.0.4
lrwxrwxrwx 1 root root  17 Mar  9 12:50 /usr/lib64/libgdal.so.26 -> libgdal.so.26.0.4
-rwxr-xr-x 1 root root 23M Mar  9 12:51 /usr/lib64/libgdal.so.26.0.4
```

**Comment by mtfelian** [comment]
Common setup - usually if your system/container setup corresponds to what was coded - it works out of box. 

You probably noticed 
```
#cgo linux  pkg-config: gdal
#cgo darwin pkg-config: gdal
#cgo windows LDFLAGS: -Lc:/gdal/release-1600-x64/lib -lgdal_i
#cgo windows CFLAGS: -IC:/gdal/release-1600-x64/include
```
compiler options which follows includes but precedes `import "C"`

This passes flags to cgo compiler. 

But for linux it uses pkg-config which is configured via `gdal.pc` file. 

Basically you can try to overwrite cgo compiler options by writing something like
```
#cgo linux LDFLAGS: ...
#cgo linux CFLAGS: ...
```
in your package where you are importing this package but i am not sure that it will work :)

Also you may read the following: https://stackoverflow.com/questions/28710276/override-an-external-packages-cgo-compiler-and-linker-flags

**Comment by therox** [comment]
No effect after overriding this options manually :(

Trying different OSes and...

works like a charm out of box on 
   ubuntu 18.04 (gdal 2.2.3go 1.10.4), 19.10 (2.4.2, go 1.12),
   fedora 28(gdal 2.2.4, go ), 29(gdal 2.3.2. go 1.11.13), 30(gdal 2.3.2, go 1.12), 31(gdal 2.3.2, go 1.13.11)

Do not work: 
   ubuntu 20.04 (gdal 3.0.4, go 1.13.8), 20.10 (gdal 3.0.4, go 1.14.3), 
   fedora 26(gdal 2.1.3, go 1.8.7), 32(gdal 3.0.4, go 1.14.4)

**Comment by mtfelian** [comment]
No idea really except some caveats with library path. I am now fighting with similar kind of problem: 

- when i import eccodes library wrapper or gdal wrapper (this project) separately, it works. When i import it both, it do not sees libraries. For now no idea what happens and no way of overwriting paths works. Searching for solution also.

**Comment by mtfelian** [comment]
@therox I found out that this will not compile with GDAL 3 (but may work with it being compiled on GDAL 2, with crash at appropriate call of not-existent function). Read the migration guide: https://github.com/OSGeo/gdal/blob/master/gdal/MIGRATION_GUIDE.TXT

**Comment by therox** [comment]
> @therox I found out that this will not compile with GDAL 3 (but may work with it being compiled on GDAL 2, with crash at appropriate call of not-existent function). Read the migration guide: https://github.com/OSGeo/gdal/blob/master/gdal/MIGRATION_GUIDE.TXT
> Some entities like `C.OSRStripCTParms` were removed in GDAL 3.
Wow, you're right, it seems this bindings are for GDAL v >2.1 and < 3
> Your test systems with Debian 9 and Fedora 26 are probably producing different error messages and both needs newer Go.
No, I've tested on debian 9 with go 1.14, same error.
> But required changes are pretty straightforward and you can DIY in your fork of this. Just remove methods with call to appropriate C funcs which are no more existent and tweak other changes as per needed.
I'll try, thanks for investigation.

It seems there must be release branches for appropriate gdal release.
