### ISSUE TITLE
BUILD on Mac M1, Return ERROR: ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by ningfc** [lukeroth/gdal#75]
OS version = macOS Big Sur 11.6
CPU = Apple M1

$go get github.com/lukeroth/gdal
\# github.com/lukeroth/gdal
Undefined symbols for architecture arm64:
  "_CPLGetConfigOption", referenced from:
      __cgo_20816c41b399_Cfunc_CPLGetConfigOption in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_CPLGetConfigOption)
  "_CPLSetConfigOption", referenced from:
      __cgo_20816c41b399_Cfunc_CPLSetConfigOption in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_CPLSetConfigOption)
  "_GDALAddBand", referenced from:
      __cgo_20816c41b399_Cfunc_GDALAddBand in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_GDALAddBand)
  "_GDALAllRegister", referenced from:
      __cgo_20816c41b399_Cfunc_GDALAllRegister in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_GDALAllRegister)
..................
  "_VSIFOpenL", referenced from:
      __cgo_20816c41b399_Cfunc_VSIFOpenL in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_VSIFOpenL)
  "_VSIFReadL", referenced from:
      __cgo_20816c41b399_Cfunc_VSIFReadL in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_VSIFReadL)
  "_VSIReadDirRecursive", referenced from:
      __cgo_20816c41b399_Cfunc_VSIReadDirRecursive in _x003.o
     (maybe you meant: __cgo_20816c41b399_Cfunc_VSIReadDirRecursive)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kallsyms** [comment]
Looks like #69 (and #72) are only tagged for amd64, so the linker flags aren't getting applied to arm64 builds. I don't see why those need to be arch-specific, but until that's changed you can also build by setting the envvars `CGO_CFLAGS="-I$(brew --prefix)/opt/gdal/include" CGO_LDFLAGS="-L$(brew --prefix)/opt/gdal/lib -lgdal"`

**Comment by ningfc** [comment]
Yes, I resolved it, not just setting CGO_CFLAGS & CGO_LDFLAGS, also need copy c_darwin_amd64.go to c_darwin_arm64.go and edit the first line of c_darwin_arm64.go, like this
< // +build darwin,amd64
---
> // +build darwin,arm64
Then, I run go build, successful. 😄
