### ISSUE TITLE
Go 1.21 issue

### ISSUE THREAD

**Issue by alienatorZ** [lukeroth/gdal#97]
Hello this error popped up after I upgraded to go 1.21

github.com/lukeroth/gdal@v0.0.0-20230818145556-62d5095a1cda/algorithms.go:528:4: unknown field nSizeOfStructure in struct literal of type _Ctype_struct___3 

I tried to clear my mod cache and  go mod tidy again but I keep getting the same error.

Thanks!

**Comment by ttrubel** [comment]
I solved this issue by upgrading gdal to version 3.6

**Comment by alienatorZ** [comment]
That resolved it.
Thank you @ttrubel !
